<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '"{number}" is not a valid card number' => '{number} non è un numero di carta valido',
    '"{value}" does not seem to be a valid phone number.' => '{value} sembra non essere un numero di telefono valido',
    '"{value}" is not a valid email address.' => '{value} non è un indirizzo email valido',
    'A maximum of {value, number} {value, plural, one{email is} other{emails are}} allowed.' => 'È consentito un massimo di {value} email}',
    'At least {value, number} {value, plural, one{email is} other{emails are}} required.' => 'È necessario inserire almeno {value} email.',
    'Country is required for phone validation.' => 'La nazione è obbligatoria per validare il telefono',
    'Invalid CVV "{cvv}"' => 'CVV non valido',
    'Invalid expiry month/year "{expiry}"' => 'Scadenza mese/anno "{expiry}" non valida',
    'Invalid holder name "{holder}"' => 'Intestatario "{holder}" non valido',
    'Unexpected or unrecognized phone number format.' => 'Formato numero non riconosciuto o non valido',
    'Unsupported card number "{number}"' => 'Numero carta "{number}" non supportato',
];
